### ISSUE TITLE
Failed to add plugin cordova-plugin-iosrtc from China

### ISSUE THREAD

**Issue by octopusjames** [cordova-rtc/cordova-plugin-iosrtc-sample#10]
Hello,

I can successfully clone cordova-plugin-iosrtc-sample, but can't install plugin "cordova-plugin-iosrtc".  I tried three ways but neither works.
1. I input "cordova platform add ios --verbose", I can see ios platform libs and other plugins added successfuly but plugin "cordova-plugin-iosrtc" hanged forever with logging "Running command: npm install git+https://github.com/cordova-rtc/cordova-plugin-iosrtc.git#master --save-dev"
2. Then I input "cordova plugin add cordova-plugin-iosrtc --verbose", the same thing happend as procedure 1.
3. Then I try local way by cloning "cordova-plugin-iosrtc" first and then input "cordova plugin add ../cordova-plugin-iosrtc", this time there prompt error logging "jse_shortmsg: 'Could not determine package name from output:\n' + 'removed 7 packages, and changed 1 package in 581ms', jse_info: {}"

Could you pls help me out here?  Many thanks. ：）

--------
macOS Big Sur 11.1（M1 chip）
Xcode 12.3
cordova 10.0.0
cordova iOS 6.1.1

**Comment by hthetiot** [comment]
Thank you I will check.

**Comment by octopusjames** [comment]
Thank you for update and sync my progressing

I noticed even git clone usually got failed so maybe the reason result from github.com is speed-limited in China.
In order to speed up github accessing I tried use socks5 proxy or modify real IP in /etc/hosts but neither works. At last I found the solution by forking "cordova-plugin-iosrtc" and "cordova-plugin-iosrtc-sample" to a git website in China -- "gitee.com", then git clone always get succeeded and quickly.

So, I modify packge.json like this
```
"devDependencies": {
    ...
    "cordova-plugin-iosrtc": "git+https://gitee.com/octopusjames/cordova-plugin-iosrtc.git#master"
    ...
  },
```
But plugin install still failed and the logging is
```
Discovered plugin "cordova-plugin-iosrtc". Adding it to the project
No scripts found for hook "before_plugin_add".
Calling plugman.fetch on plugin "git+https://gitee.com/octopusjames/cordova-plugin-iosrtc.git#master"
fetch: Installing git+https://gitee.com/octopusjames/cordova-plugin-iosrtc.git#master to /Users/mj/Work/code/cordova-plugin-iosrtc-sample
Running command: npm install git+https://gitee.com/octopusjames/cordova-plugin-iosrtc.git#master --save-dev
Command finished with error code 0: npm install,git+https://gitee.com/octopusjames/cordova-plugin-iosrtc.git#master,--save-dev
Failed to fetch plugin git+https://gitee.com/octopusjames/cordova-plugin-iosrtc.git#master via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
CordovaError: CordovaError: Could not determine package name from output:
up to date in 3m
```

***
If I clone a clean sample and directly input "npm install https://gitee.com/octopusjames/cordova-plugin-iosrtc.git", it will succeed.

**Comment by hthetiot** [comment]
> the solution by forking "cordova-plugin-iosrtc" and "cordova-plugin-iosrtc-sample" to a git website in China -- "gitee.com", then git clone always get succeeded and quickly.

I dont think it come from us, Travis Continious integration as no issue.
This plugin is quite big sue WebRTC.Framework build, may be Great Firewall of China is causing some issue.
Did you try VPN ?

**Comment by octopusjames** [comment]
Yes, I tried VPN with a shadowsocket proxy

**Comment by hthetiot** [comment]
I may have a idea why, keep you posted

**Comment by octopusjames** [comment]
Thank you very much

**Comment by hthetiot** [comment]
Can you do a traceroute (https://wikipedia.org/wiki/Traceroute)

Also this issue should be main repository cordova-plugin-iosrtc https://github.com/cordova-rtc/cordova-plugin-iosrtc

That would help a lot.

**Comment by hthetiot** [comment]
You can i install from local if you got clone works, you may have issues with npm and got config not sure.

> cordova plugin install ../my-fork-of-iosrtc

**Comment by hthetiot** [comment]
Closed due innactivity.
