### ISSUE TITLE
Video gets on top of all elements

### ISSUE THREAD

**Issue by neeact** [cordova-rtc/cordova-plugin-iosrtc-sample#4]
Hi, 

we are building a video chat application using Cordova but we have a huge problem in **iOS**: when the video is rendered in the screen, it gets on top of all other elements.

We need to put other elements (like hangup and mute buttons, etc) on top of the video, but no matter what we do, the video always get on top of the remaining elements.

All investigation we have made points to the "**allowsInlineMediaPlayback**", but we have already set the Cordova preference preference name="AllowInlineMediaPlayback" value="true" + playsinline attribute on the video elements, but the problem persists.

We have tried everything: z-index and other CSS properties are not working.

Is there a problem with the iosrtc plugin or do you have a solution for this?
Thank you!
-ct-

**Comment by hthetiot** [comment]
Can you test this sample repository and run it and confirm that elements appear on top of video like in the README:
- https://github.com/cordova-rtc/cordova-plugin-iosrtc-sample/blob/master/art/jssip_freeswitch_1.png
