### ISSUE TITLE
Audio permission not asked on Replacing content of www/index.html with simple gum call

### ISSUE THREAD

**Issue by xdev2381** [cordova-rtc/cordova-plugin-iosrtc-sample#5]
Hi,
I have cloned the sample app and built it and run it on iPad device running ios14 qnd ios14.1. It is working fine. But when I replace the content of www folder with a simple html and (js) wit a simple getUserMedia call, the app is asking only for video permissions. the Video stream from camera starts playing in video element without audio. I dont have that much experience with ios applications, So i am not able to make that much out of the logs. I request to someone to give me a direction how to move from here.
[Logs: Logs.txt](https://github.com/cordova-rtc/cordova-plugin-iosrtc-sample/files/5436733/Logs.txt)

Cordova version: 10.0.0:
Cordova iOS version : "^6.1.1",
Plugin version : "github master" "cordova-plugin-iosrtc": "git+https://github.com/cordova-rtc/cordova-plugin-iosrtc.git#master",,
iOS version : 14.1
Xcode version :12.1 Build version 12A7403

index.html

```html
<!DOCTYPE html>
<html>

<head>
    <meta http-equiv="Content-Security-Policy"
        content=" media-src * blob: ; script-src * 'self' 'unsafe-inline' 'unsafe-eval'; connect-src * blob: http: https: 'self' 'unsafe-inline' 'unsafe-eval' http://*/* https://*/* https://*:* ">
    <meta name="format-detection" content="telephone=no">
    <meta name="msapplication-tap-highlight" content="no">
    <meta name="viewport"
        content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no,viewport-fit=cover">

    <script type="text/javascript" src="cordova.js"></script>
    <script type="text/javascript" src="js/index.js"></script>
</head>

<body>
    <div class="app">
        <div class="remote-stream">
            <video id='video' autoplay="autoplay" playsinline="playsinline"></video>
        </div>
        <div>
            <button id="openCamera">Open Camera</button>
            <p id="status"></p>
        </div>
</body>
<script>
    let video = document.getElementById("video");
    let status = document.getElementById("status");
    let openCamera = document.getElementById("openCamera");

    const onClickOpenCamera = () => {
        openCamera.style.visibility = "hidden";
        navigator.mediaDevices.getUserMedia({ audio: true, video: true })
            .then((stream) => {
                video.srcObject = stream;
                status.innerHTML = "Got the stream.";
            })
            .catch((error) => { status.innerHTML = JSON.stringify(error); });
    }

    openCamera.addEventListener('click', onClickOpenCamera);

</script>

</html>
```

index.js

```js
document.addEventListener('deviceready', onDeviceReady, false);

function onDeviceReady() {
    // Cordova is now initialized. Have fun!

    console.log('Running cordova-' + cordova.platformId + '@' + cordova.version);
    console.log('device.platform', device.platform);
    if (device.platform === 'iOS') {
        console.log('REGISTERING');
        cordova.plugins.iosrtc.registerGlobals();
    }
}
```

**Comment by xdev2381** [comment]
I think it is not a problem with the sample app. It has to be either an issue with the plugin or I am doing something silly. I am able to reproduce this in  a newly generated Cordova app also
* cordova create cordova-ios-rtc-test1 com.xxxx.app CordovaIosRtcTest1
* Cd cordova-ios-rtc-test1 
* cordova plugin add cordova-plugin-iosrtc 
* Replace www folder with new www folder with new index.html and index.js
* cordova platform add ios
* Build and deploy in device (iPad)
The index.html and index.js and info.plist is attached
This time the device plugin was also not used
[html-and-js.zip](https://github.com/cordova-rtc/cordova-plugin-iosrtc-sample/files/5444466/html-and-js.zip)
[CordovaIosRtcTest1-Info.plist.zip](https://github.com/cordova-rtc/cordova-plugin-iosrtc-sample/files/5444434/CordovaIosRtcTest1-Info.plist.zip)

**Comment by hthetiot** [comment]
@xdev2381 simple question; your index.html is just displaying local video, did you expect to hear yourself ?
If so that normal you are not earing yourself, you can only hear remote stream not local ones.

**Comment by xdev2381** [comment]
Yes I was expecting to hear myself here. The thing bothering me here is that the audio permission is not being asked (only camera permission is asked) at the getusermedia call with audio: true and video: true. We have a webrtc web application for conferencing. I had ported that application successfully to ios using cordova-plugin-iosrtc earlier (6 months back). But when i try to do the same now the application is asking for only camera permission at place of a similar getusermedia call. I am trying to recall anything that I might have done in the past to fix this.  That is why I removed everything and added only the getusermedia call in the application and trying to play video and audio in the video element.

**Comment by hthetiot** [comment]
You should see microphone permission when peer connect the first time, that due some of the implementation nature.

 iosRTC also expose api to ask permissions.https://github.com/cordova-rtc/cordova-plugin-iosrtc/blob/master/docs/iosrtc.md#iosrtcrequestpermission
